---
  - name: Start CRC 1.7.0 and deploy Kogito Operator and CLI
    hosts: localhost
    gather_facts: true

    vars:
      kogito_tag: "0.8.0"
      ram: "16384" #MB
      libvirt_version: "4.3.1"
      kube_password: "{{ lookup('file', '/home/{{ ansible_user_id }}/.crc/cache/crc_libvirt_{{ libvirt_version }}/kubeadmin-password') }}"

    vars_prompt:
      - name: "nameSpace"
        prompt: "Insert your Project Name/ NameSpace"
      - name: "PullSecret"
        prompt: "Insert your Pull secret"

    tasks:
      - debug: msg="Project Name {{ nameSpace }}"

      - name: Clone Kogito Operator repo
        become: false
        git:
          repo: "https://github.com/kiegroup/kogito-cloud-operator.git"
          dest: "/tmp/kogito-cloud-operator"
          accept_hostkey: true
          version: master

      - name: Copy Kogito cli
        get_url:
          url: "https://github.com/kiegroup/kogito-cloud-operator/releases/download/v{{ kogito_tag }}/kogito-{{ kogito_tag }}-linux-amd64.tar.gz"
          dest: "/tmp/kogito-{{ kogito_tag }}-linux-amd64.tar.gz"

      - name: Extract Kogito cli archive
        unarchive:
          src: "/tmp/kogito-{{ kogito_tag }}-linux-amd64.tar.gz"
          dest: "/tmp/"

      - name: Check that oc exists in /home/{{ansible_user_id}}/.local/bin/
        stat:
          path: "/home/{{ ansible_user_id }}/.local/bin/kogito"
        register: stat_result

      - name: Creates user home kogito dir
        file:
          path: "/home/{{ ansible_user_id}}/.local/bin/"
          state: directory
        when: stat_result.stat.exists == False

      - name: Move kogito from /tmp to /home/{{ansible_user_id}}/.local/bin
        command: "mv /tmp/kogito /home/{{ansible_user_id}}/.local/bin/"
        when: stat_result.stat.exists == False

      - name: CRC setup
        shell: "crc setup"
        register: crc_result

      - debug: msg="{{ crc_result }}"

      - name: Write pull secret
        copy:
          content: "{{ PullSecret }}"
          dest: "~/.crc/crc-pull-secret"

      - name: Start CRC with {{ ram }}MB (~ 3 minutes)
        shell: "crc start -m {{ ram }} -p ~/.crc/crc-pull-secret"

      - name: Login crc
        shell: "oc login -u kubeadmin -p {{ kube_password }} https://api.crc.testing:6443"

      - name: Create {{ nameSpace }}
        shell: "oc new-project {{ nameSpace }}"

      - name: Use {{ nameSpace }} proect
        shell: "oc project {{ nameSpace }}"

      #- name: Try to create all kogito
      #  shell: "oc apply -f https://raw.githubusercontent.com/kiegroup/kogito-images/master/kogito-imagestream.yaml -n {{ nameSpace }} "

      - name: Install Kogito apps
        shell: "oc apply -f /tmp/kogito-cloud-operator/deploy/crds/app.kiegroup.org_kogitoapps_crd.yaml"
        register: install_kogito_apps_result

      - debug: msg="{{ install_kogito_apps_result }}"

      - name: Install Kogito data index
        shell: "oc apply -f /tmp/kogito-cloud-operator/deploy/crds/app.kiegroup.org_kogitodataindices_crd.yaml"
        register: install_kogito_data_index_result

      - debug: msg="{{ install_kogito_data_index_result }}"

      - name: Install Kogito infras
        shell: "oc apply -f /tmp/kogito-cloud-operator/deploy/crds/app.kiegroup.org_kogitoinfras_crd.yaml"
        register: install_kogito_infras_result

      - debug: msg="{{ install_kogito_infras_result }}"

      - name: Install Kogito jobs services
        shell: "oc apply -f /tmp/kogito-cloud-operator/deploy/crds/app.kiegroup.org_kogitojobsservices_crd.yaml"
        register: install_kogito_jobs_result

      - debug: msg="{{ install_kogito_jobs_result }}"

      - name: Install Kogito operator
        shell: "oc apply -f /tmp/kogito-cloud-operator/deploy/operator.yaml"
        register: install_kogito_operator_result

      - debug: msg="{{ install_kogito_operator_result }}"

      - name: Install Kogito role
        shell: "oc apply -f /tmp/kogito-cloud-operator/deploy/role.yaml"
        register: install_kogito_role_result

      - debug: msg="{{ install_kogito_role_result }}"

      - name: Install Kogito role binding
        shell: "oc apply -f /tmp/kogito-cloud-operator/deploy/role_binding.yaml"
        register: install_kogito_role_binding_result

      - debug: msg="{{ install_kogito_role_binding_result }}"

      - name: Install Kogito service account
        shell: "oc apply -f /tmp/kogito-cloud-operator/deploy/service_account.yaml"
        register: install_kogito_service_account_result

      - debug: msg="{{ install_kogito_service_account_result }}"



      - name: Kogito use {{ nameSpace }}
        shell: "kogito use-project {{ nameSpace }}"
        register: kogito_use_project_result
        ignore_errors: yes #kogito-operator Operator seems to be created in the namespace '****', but there's no available pods replicas deployed

      - debug: msg="{{ kogito_use_project_result }}"

      - name: Deploy Drools-quarkus-example
        shell: "kogito deploy-service example-quarkus https://github.com/kiegroup/kogito-examples/ --context-dir=drools-quarkus-example"
        register: install_drools_quarkus_example
        ignore_errors: yes

      - debug: msg="{{ install_drools_quarkus_example }}"

      - name: Open browser
        shell: "crc console"

      - debug: msg="Your Kube Password is {{ kube_password }}"